version: '3.7'
services:
  proxy:
    container_name: cat-pinterest-proxy
    image: nginx:1.24-alpine-slim
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    depends_on:
      cat-pinterest-api:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      - cat-pinterest-net
      

  cat-pinterest-api:
    container_name: cat-pinterest-api
    image: cat-pinterest-api
    build:
      context: ./api/
    networks:
      - cat-pinterest-net
    env_file:
      - ./api/.env
    depends_on:
      cat-pinterest-api-pg:
        condition: service_healthy
    ports:
      - "3000:3000"

  cat-pinterest-front:
    container_name: cat-pinterest-front
    image: cat-pinterest-front
    build:
      context: ./front/
      args:
        NODE_ENV: prod
        VITE_CATS_API_KEY: live_ie8Toulv441tyBHwi2gSyIeVA04anu9FKRE4JI6otJcPH7ZLMlU156Prer9xtbeV
        VITE_API_URL: http://localhost:3000
    networks:
      - cat-pinterest-net

  cat-pinterest-api-pg:
    container_name: cat-pinterest-api-pg
    image: postgres:14
    networks:
      - cat-pinterest-net
    env_file:
      - ./api/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

networks:
  cat-pinterest-net:
